<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9541O0Q" name="Test" tests="13" failures="1" timestamp="11 Sep 2023 14:46:17 GMT" time="12.136" errors="0">
  <testcase name="testA1" time="0.024" classname="org.rerunn.A"/>
  <testcase name="testA2" time="4.744" classname="org.rerunn.A">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="2.56" classname="org.rerunn.A">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="2.273" classname="org.rerunn.A">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="2.413" classname="org.rerunn.A"/>
  <testcase name="testA3" time="0.004" classname="org.rerunn.A"/>
  <testcase name="testB1" time="0.001" classname="org.rerunn.B"/>
  <testcase name="testB2" time="0.003" classname="org.rerunn.B">
    <skipped/>
  </testcase> <!-- testB2 -->
  <testcase name="testB2" time="0.002" classname="org.rerunn.B">
    <skipped/>
  </testcase> <!-- testB2 -->
  <testcase name="testB2" time="0.003" classname="org.rerunn.B">
    <skipped/>
  </testcase> <!-- testB2 -->
  <testcase name="testB2" time="0.002" classname="org.rerunn.B">
    <skipped/>
  </testcase> <!-- testB2 -->
  <testcase name="testB2" time="0.001" classname="org.rerunn.B">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.rerunn.B.testB2(B.java:18)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testB2 -->
  <testcase name="testB3" time="0.019" classname="org.rerunn.B"/>
</testsuite> <!-- Test -->
